// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chat/server/v1/event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat.Server.V1 {

  /// <summary>Holder for reflection information generated from chat/server/v1/event.proto</summary>
  public static partial class EventReflection {

    #region Descriptor
    /// <summary>File descriptor for chat/server/v1/event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpjaGF0L3NlcnZlci92MS9ldmVudC5wcm90bxIOY2hhdC5zZXJ2ZXIudjEa",
            "GWNoYXQvZ2FtZS92MS9zZXJ2ZXIucHJvdG8aIWNoYXQvc2VydmVyL3YxL2Vy",
            "cm9yX2V2ZW50cy5wcm90bxogY2hhdC9zZXJ2ZXIvdjEvcm9vbV9ldmVudHMu",
            "cHJvdG8i/AQKC1NlcnZlckV2ZW50EhgKB3ZlcnNpb24YASABKAlSB3ZlcnNp",
            "b24SMwoFZXJyb3IYAiABKAsyGy5jaGF0LnNlcnZlci52MS5TZXJ2ZXJFcnJv",
            "ckgAUgVlcnJvchIxCgVyb29tcxgDIAEoCzIZLmNoYXQuc2VydmVyLnYxLlJv",
            "b21JbmZvc0gAUgVyb29tcxI9Cgtyb29tX2pvaW5lZBgEIAEoCzIaLmNoYXQu",
            "c2VydmVyLnYxLlJvb21Kb2luZWRIAFIKcm9vbUpvaW5lZBI3Cglyb29tX2xl",
            "ZnQYBSABKAsyGC5jaGF0LnNlcnZlci52MS5Sb29tTGVmdEgAUghyb29tTGVm",
            "dBJKChByb29tX3VzZXJfam9pbmVkGAYgASgLMh4uY2hhdC5zZXJ2ZXIudjEu",
            "Um9vbVVzZXJKb2luZWRIAFIOcm9vbVVzZXJKb2luZWQSRAoOcm9vbV91c2Vy",
            "X2xlZnQYByABKAsyHC5jaGF0LnNlcnZlci52MS5Sb29tVXNlckxlZnRIAFIM",
            "cm9vbVVzZXJMZWZ0Ek0KEXJvb21fZ2FtZV9zdGFydGVkGAggASgLMh8uY2hh",
            "dC5zZXJ2ZXIudjEuUm9vbUdhbWVTdGFydGVkSABSD3Jvb21HYW1lU3RhcnRl",
            "ZBJNChFyb29tX2dhbWVfc3RvcHBlZBgJIAEoCzIfLmNoYXQuc2VydmVyLnYx",
            "LlJvb21HYW1lU3RvcHBlZEgAUg9yb29tR2FtZVN0b3BwZWQSOwoLc2VydmVy",
            "X3RpY2sYCiABKAsyGC5jaGF0LmdhbWUudjEuU2VydmVyVGlja0gAUgpzZXJ2",
            "ZXJUaWNrQgYKBGRhdGFCgwEKEmNvbS5jaGF0LnNlcnZlci52MUIKRXZlbnRQ",
            "cm90b1ABWgcuL3Byb3RvogIDQ1NYqgIOQ2hhdC5TZXJ2ZXIuVjHKAg5DaGF0",
            "XFNlcnZlclxWMeICGkNoYXRcU2VydmVyXFYxXEdQQk1ldGFkYXRh6gIQQ2hh",
            "dDo6U2VydmVyOjpWMWIIZWRpdGlvbnNw6Ac="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Chat.Game.V1.ServerReflection.Descriptor, global::Chat.Server.V1.ErrorEventsReflection.Descriptor, global::Chat.Server.V1.RoomEventsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Server.V1.ServerEvent), global::Chat.Server.V1.ServerEvent.Parser, new[]{ "Version", "Error", "Rooms", "RoomJoined", "RoomLeft", "RoomUserJoined", "RoomUserLeft", "RoomGameStarted", "RoomGameStopped", "ServerTick" }, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ServerEvent : pb::IMessage<ServerEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerEvent> _parser = new pb::MessageParser<ServerEvent>(() => new ServerEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Server.V1.EventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerEvent(ServerEvent other) : this() {
      version_ = other.version_;
      switch (other.DataCase) {
        case DataOneofCase.Error:
          Error = other.Error.Clone();
          break;
        case DataOneofCase.Rooms:
          Rooms = other.Rooms.Clone();
          break;
        case DataOneofCase.RoomJoined:
          RoomJoined = other.RoomJoined.Clone();
          break;
        case DataOneofCase.RoomLeft:
          RoomLeft = other.RoomLeft.Clone();
          break;
        case DataOneofCase.RoomUserJoined:
          RoomUserJoined = other.RoomUserJoined.Clone();
          break;
        case DataOneofCase.RoomUserLeft:
          RoomUserLeft = other.RoomUserLeft.Clone();
          break;
        case DataOneofCase.RoomGameStarted:
          RoomGameStarted = other.RoomGameStarted.Clone();
          break;
        case DataOneofCase.RoomGameStopped:
          RoomGameStopped = other.RoomGameStopped.Clone();
          break;
        case DataOneofCase.ServerTick:
          ServerTick = other.ServerTick.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerEvent Clone() {
      return new ServerEvent(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private readonly static string VersionDefaultValue = "";

    private string version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_ ?? VersionDefaultValue; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "version" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVersion {
      get { return version_ != null; }
    }
    /// <summary>Clears the value of the "version" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVersion() {
      version_ = null;
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.ServerError Error {
      get { return dataCase_ == DataOneofCase.Error ? (global::Chat.Server.V1.ServerError) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Error;
      }
    }

    /// <summary>Field number for the "rooms" field.</summary>
    public const int RoomsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomInfos Rooms {
      get { return dataCase_ == DataOneofCase.Rooms ? (global::Chat.Server.V1.RoomInfos) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Rooms;
      }
    }

    /// <summary>Field number for the "room_joined" field.</summary>
    public const int RoomJoinedFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomJoined RoomJoined {
      get { return dataCase_ == DataOneofCase.RoomJoined ? (global::Chat.Server.V1.RoomJoined) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RoomJoined;
      }
    }

    /// <summary>Field number for the "room_left" field.</summary>
    public const int RoomLeftFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomLeft RoomLeft {
      get { return dataCase_ == DataOneofCase.RoomLeft ? (global::Chat.Server.V1.RoomLeft) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RoomLeft;
      }
    }

    /// <summary>Field number for the "room_user_joined" field.</summary>
    public const int RoomUserJoinedFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomUserJoined RoomUserJoined {
      get { return dataCase_ == DataOneofCase.RoomUserJoined ? (global::Chat.Server.V1.RoomUserJoined) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RoomUserJoined;
      }
    }

    /// <summary>Field number for the "room_user_left" field.</summary>
    public const int RoomUserLeftFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomUserLeft RoomUserLeft {
      get { return dataCase_ == DataOneofCase.RoomUserLeft ? (global::Chat.Server.V1.RoomUserLeft) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RoomUserLeft;
      }
    }

    /// <summary>Field number for the "room_game_started" field.</summary>
    public const int RoomGameStartedFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomGameStarted RoomGameStarted {
      get { return dataCase_ == DataOneofCase.RoomGameStarted ? (global::Chat.Server.V1.RoomGameStarted) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RoomGameStarted;
      }
    }

    /// <summary>Field number for the "room_game_stopped" field.</summary>
    public const int RoomGameStoppedFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Server.V1.RoomGameStopped RoomGameStopped {
      get { return dataCase_ == DataOneofCase.RoomGameStopped ? (global::Chat.Server.V1.RoomGameStopped) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RoomGameStopped;
      }
    }

    /// <summary>Field number for the "server_tick" field.</summary>
    public const int ServerTickFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Game.V1.ServerTick ServerTick {
      get { return dataCase_ == DataOneofCase.ServerTick ? (global::Chat.Game.V1.ServerTick) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.ServerTick;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Error = 2,
      Rooms = 3,
      RoomJoined = 4,
      RoomLeft = 5,
      RoomUserJoined = 6,
      RoomUserLeft = 7,
      RoomGameStarted = 8,
      RoomGameStopped = 9,
      ServerTick = 10,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (!object.Equals(Error, other.Error)) return false;
      if (!object.Equals(Rooms, other.Rooms)) return false;
      if (!object.Equals(RoomJoined, other.RoomJoined)) return false;
      if (!object.Equals(RoomLeft, other.RoomLeft)) return false;
      if (!object.Equals(RoomUserJoined, other.RoomUserJoined)) return false;
      if (!object.Equals(RoomUserLeft, other.RoomUserLeft)) return false;
      if (!object.Equals(RoomGameStarted, other.RoomGameStarted)) return false;
      if (!object.Equals(RoomGameStopped, other.RoomGameStopped)) return false;
      if (!object.Equals(ServerTick, other.ServerTick)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasVersion) hash ^= Version.GetHashCode();
      if (dataCase_ == DataOneofCase.Error) hash ^= Error.GetHashCode();
      if (dataCase_ == DataOneofCase.Rooms) hash ^= Rooms.GetHashCode();
      if (dataCase_ == DataOneofCase.RoomJoined) hash ^= RoomJoined.GetHashCode();
      if (dataCase_ == DataOneofCase.RoomLeft) hash ^= RoomLeft.GetHashCode();
      if (dataCase_ == DataOneofCase.RoomUserJoined) hash ^= RoomUserJoined.GetHashCode();
      if (dataCase_ == DataOneofCase.RoomUserLeft) hash ^= RoomUserLeft.GetHashCode();
      if (dataCase_ == DataOneofCase.RoomGameStarted) hash ^= RoomGameStarted.GetHashCode();
      if (dataCase_ == DataOneofCase.RoomGameStopped) hash ^= RoomGameStopped.GetHashCode();
      if (dataCase_ == DataOneofCase.ServerTick) hash ^= ServerTick.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasVersion) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      if (dataCase_ == DataOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (dataCase_ == DataOneofCase.Rooms) {
        output.WriteRawTag(26);
        output.WriteMessage(Rooms);
      }
      if (dataCase_ == DataOneofCase.RoomJoined) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomJoined);
      }
      if (dataCase_ == DataOneofCase.RoomLeft) {
        output.WriteRawTag(42);
        output.WriteMessage(RoomLeft);
      }
      if (dataCase_ == DataOneofCase.RoomUserJoined) {
        output.WriteRawTag(50);
        output.WriteMessage(RoomUserJoined);
      }
      if (dataCase_ == DataOneofCase.RoomUserLeft) {
        output.WriteRawTag(58);
        output.WriteMessage(RoomUserLeft);
      }
      if (dataCase_ == DataOneofCase.RoomGameStarted) {
        output.WriteRawTag(66);
        output.WriteMessage(RoomGameStarted);
      }
      if (dataCase_ == DataOneofCase.RoomGameStopped) {
        output.WriteRawTag(74);
        output.WriteMessage(RoomGameStopped);
      }
      if (dataCase_ == DataOneofCase.ServerTick) {
        output.WriteRawTag(82);
        output.WriteMessage(ServerTick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasVersion) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      if (dataCase_ == DataOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (dataCase_ == DataOneofCase.Rooms) {
        output.WriteRawTag(26);
        output.WriteMessage(Rooms);
      }
      if (dataCase_ == DataOneofCase.RoomJoined) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomJoined);
      }
      if (dataCase_ == DataOneofCase.RoomLeft) {
        output.WriteRawTag(42);
        output.WriteMessage(RoomLeft);
      }
      if (dataCase_ == DataOneofCase.RoomUserJoined) {
        output.WriteRawTag(50);
        output.WriteMessage(RoomUserJoined);
      }
      if (dataCase_ == DataOneofCase.RoomUserLeft) {
        output.WriteRawTag(58);
        output.WriteMessage(RoomUserLeft);
      }
      if (dataCase_ == DataOneofCase.RoomGameStarted) {
        output.WriteRawTag(66);
        output.WriteMessage(RoomGameStarted);
      }
      if (dataCase_ == DataOneofCase.RoomGameStopped) {
        output.WriteRawTag(74);
        output.WriteMessage(RoomGameStopped);
      }
      if (dataCase_ == DataOneofCase.ServerTick) {
        output.WriteRawTag(82);
        output.WriteMessage(ServerTick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasVersion) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (dataCase_ == DataOneofCase.Error) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (dataCase_ == DataOneofCase.Rooms) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rooms);
      }
      if (dataCase_ == DataOneofCase.RoomJoined) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomJoined);
      }
      if (dataCase_ == DataOneofCase.RoomLeft) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomLeft);
      }
      if (dataCase_ == DataOneofCase.RoomUserJoined) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomUserJoined);
      }
      if (dataCase_ == DataOneofCase.RoomUserLeft) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomUserLeft);
      }
      if (dataCase_ == DataOneofCase.RoomGameStarted) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomGameStarted);
      }
      if (dataCase_ == DataOneofCase.RoomGameStopped) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomGameStopped);
      }
      if (dataCase_ == DataOneofCase.ServerTick) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerTick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerEvent other) {
      if (other == null) {
        return;
      }
      if (other.HasVersion) {
        Version = other.Version;
      }
      switch (other.DataCase) {
        case DataOneofCase.Error:
          if (Error == null) {
            Error = new global::Chat.Server.V1.ServerError();
          }
          Error.MergeFrom(other.Error);
          break;
        case DataOneofCase.Rooms:
          if (Rooms == null) {
            Rooms = new global::Chat.Server.V1.RoomInfos();
          }
          Rooms.MergeFrom(other.Rooms);
          break;
        case DataOneofCase.RoomJoined:
          if (RoomJoined == null) {
            RoomJoined = new global::Chat.Server.V1.RoomJoined();
          }
          RoomJoined.MergeFrom(other.RoomJoined);
          break;
        case DataOneofCase.RoomLeft:
          if (RoomLeft == null) {
            RoomLeft = new global::Chat.Server.V1.RoomLeft();
          }
          RoomLeft.MergeFrom(other.RoomLeft);
          break;
        case DataOneofCase.RoomUserJoined:
          if (RoomUserJoined == null) {
            RoomUserJoined = new global::Chat.Server.V1.RoomUserJoined();
          }
          RoomUserJoined.MergeFrom(other.RoomUserJoined);
          break;
        case DataOneofCase.RoomUserLeft:
          if (RoomUserLeft == null) {
            RoomUserLeft = new global::Chat.Server.V1.RoomUserLeft();
          }
          RoomUserLeft.MergeFrom(other.RoomUserLeft);
          break;
        case DataOneofCase.RoomGameStarted:
          if (RoomGameStarted == null) {
            RoomGameStarted = new global::Chat.Server.V1.RoomGameStarted();
          }
          RoomGameStarted.MergeFrom(other.RoomGameStarted);
          break;
        case DataOneofCase.RoomGameStopped:
          if (RoomGameStopped == null) {
            RoomGameStopped = new global::Chat.Server.V1.RoomGameStopped();
          }
          RoomGameStopped.MergeFrom(other.RoomGameStopped);
          break;
        case DataOneofCase.ServerTick:
          if (ServerTick == null) {
            ServerTick = new global::Chat.Game.V1.ServerTick();
          }
          ServerTick.MergeFrom(other.ServerTick);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            global::Chat.Server.V1.ServerError subBuilder = new global::Chat.Server.V1.ServerError();
            if (dataCase_ == DataOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
          case 26: {
            global::Chat.Server.V1.RoomInfos subBuilder = new global::Chat.Server.V1.RoomInfos();
            if (dataCase_ == DataOneofCase.Rooms) {
              subBuilder.MergeFrom(Rooms);
            }
            input.ReadMessage(subBuilder);
            Rooms = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Server.V1.RoomJoined subBuilder = new global::Chat.Server.V1.RoomJoined();
            if (dataCase_ == DataOneofCase.RoomJoined) {
              subBuilder.MergeFrom(RoomJoined);
            }
            input.ReadMessage(subBuilder);
            RoomJoined = subBuilder;
            break;
          }
          case 42: {
            global::Chat.Server.V1.RoomLeft subBuilder = new global::Chat.Server.V1.RoomLeft();
            if (dataCase_ == DataOneofCase.RoomLeft) {
              subBuilder.MergeFrom(RoomLeft);
            }
            input.ReadMessage(subBuilder);
            RoomLeft = subBuilder;
            break;
          }
          case 50: {
            global::Chat.Server.V1.RoomUserJoined subBuilder = new global::Chat.Server.V1.RoomUserJoined();
            if (dataCase_ == DataOneofCase.RoomUserJoined) {
              subBuilder.MergeFrom(RoomUserJoined);
            }
            input.ReadMessage(subBuilder);
            RoomUserJoined = subBuilder;
            break;
          }
          case 58: {
            global::Chat.Server.V1.RoomUserLeft subBuilder = new global::Chat.Server.V1.RoomUserLeft();
            if (dataCase_ == DataOneofCase.RoomUserLeft) {
              subBuilder.MergeFrom(RoomUserLeft);
            }
            input.ReadMessage(subBuilder);
            RoomUserLeft = subBuilder;
            break;
          }
          case 66: {
            global::Chat.Server.V1.RoomGameStarted subBuilder = new global::Chat.Server.V1.RoomGameStarted();
            if (dataCase_ == DataOneofCase.RoomGameStarted) {
              subBuilder.MergeFrom(RoomGameStarted);
            }
            input.ReadMessage(subBuilder);
            RoomGameStarted = subBuilder;
            break;
          }
          case 74: {
            global::Chat.Server.V1.RoomGameStopped subBuilder = new global::Chat.Server.V1.RoomGameStopped();
            if (dataCase_ == DataOneofCase.RoomGameStopped) {
              subBuilder.MergeFrom(RoomGameStopped);
            }
            input.ReadMessage(subBuilder);
            RoomGameStopped = subBuilder;
            break;
          }
          case 82: {
            global::Chat.Game.V1.ServerTick subBuilder = new global::Chat.Game.V1.ServerTick();
            if (dataCase_ == DataOneofCase.ServerTick) {
              subBuilder.MergeFrom(ServerTick);
            }
            input.ReadMessage(subBuilder);
            ServerTick = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            global::Chat.Server.V1.ServerError subBuilder = new global::Chat.Server.V1.ServerError();
            if (dataCase_ == DataOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
          case 26: {
            global::Chat.Server.V1.RoomInfos subBuilder = new global::Chat.Server.V1.RoomInfos();
            if (dataCase_ == DataOneofCase.Rooms) {
              subBuilder.MergeFrom(Rooms);
            }
            input.ReadMessage(subBuilder);
            Rooms = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Server.V1.RoomJoined subBuilder = new global::Chat.Server.V1.RoomJoined();
            if (dataCase_ == DataOneofCase.RoomJoined) {
              subBuilder.MergeFrom(RoomJoined);
            }
            input.ReadMessage(subBuilder);
            RoomJoined = subBuilder;
            break;
          }
          case 42: {
            global::Chat.Server.V1.RoomLeft subBuilder = new global::Chat.Server.V1.RoomLeft();
            if (dataCase_ == DataOneofCase.RoomLeft) {
              subBuilder.MergeFrom(RoomLeft);
            }
            input.ReadMessage(subBuilder);
            RoomLeft = subBuilder;
            break;
          }
          case 50: {
            global::Chat.Server.V1.RoomUserJoined subBuilder = new global::Chat.Server.V1.RoomUserJoined();
            if (dataCase_ == DataOneofCase.RoomUserJoined) {
              subBuilder.MergeFrom(RoomUserJoined);
            }
            input.ReadMessage(subBuilder);
            RoomUserJoined = subBuilder;
            break;
          }
          case 58: {
            global::Chat.Server.V1.RoomUserLeft subBuilder = new global::Chat.Server.V1.RoomUserLeft();
            if (dataCase_ == DataOneofCase.RoomUserLeft) {
              subBuilder.MergeFrom(RoomUserLeft);
            }
            input.ReadMessage(subBuilder);
            RoomUserLeft = subBuilder;
            break;
          }
          case 66: {
            global::Chat.Server.V1.RoomGameStarted subBuilder = new global::Chat.Server.V1.RoomGameStarted();
            if (dataCase_ == DataOneofCase.RoomGameStarted) {
              subBuilder.MergeFrom(RoomGameStarted);
            }
            input.ReadMessage(subBuilder);
            RoomGameStarted = subBuilder;
            break;
          }
          case 74: {
            global::Chat.Server.V1.RoomGameStopped subBuilder = new global::Chat.Server.V1.RoomGameStopped();
            if (dataCase_ == DataOneofCase.RoomGameStopped) {
              subBuilder.MergeFrom(RoomGameStopped);
            }
            input.ReadMessage(subBuilder);
            RoomGameStopped = subBuilder;
            break;
          }
          case 82: {
            global::Chat.Game.V1.ServerTick subBuilder = new global::Chat.Game.V1.ServerTick();
            if (dataCase_ == DataOneofCase.ServerTick) {
              subBuilder.MergeFrom(ServerTick);
            }
            input.ReadMessage(subBuilder);
            ServerTick = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
