// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chat/client/v1/request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat.Client.V1 {

  /// <summary>Holder for reflection information generated from chat/client/v1/request.proto</summary>
  public static partial class RequestReflection {

    #region Descriptor
    /// <summary>File descriptor for chat/client/v1/request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxjaGF0L2NsaWVudC92MS9yZXF1ZXN0LnByb3RvEg5jaGF0LmNsaWVudC52",
            "MRoZY2hhdC9jbGllbnQvdjEvZ2FtZS5wcm90bxoZY2hhdC9jbGllbnQvdjEv",
            "cm9vbS5wcm90byLjAwoNQ2xpZW50UmVxdWVzdBIYCgd2ZXJzaW9uGAEgASgJ",
            "Ugd2ZXJzaW9uEj0KC2NyZWF0ZV9yb29tGAIgASgLMhouY2hhdC5jbGllbnQu",
            "djEuQ3JlYXRlUm9vbUgAUgpjcmVhdGVSb29tEjcKCWdldF9yb29tcxgDIAEo",
            "CzIYLmNoYXQuY2xpZW50LnYxLkdldFJvb21zSABSCGdldFJvb21zEjcKCWpv",
            "aW5fcm9vbRgEIAEoCzIYLmNoYXQuY2xpZW50LnYxLkpvaW5Sb29tSABSCGpv",
            "aW5Sb29tEjoKCmxlYXZlX3Jvb20YBSABKAsyGS5jaGF0LmNsaWVudC52MS5M",
            "ZWF2ZVJvb21IAFIJbGVhdmVSb29tEj4KCnN0YXJ0X2dhbWUYBiABKAsyHS5j",
            "aGF0LmNsaWVudC52MS5Sb29tU3RhcnRHYW1lSABSCXN0YXJ0R2FtZRI7Cglz",
            "dG9wX2dhbWUYByABKAsyHC5jaGF0LmNsaWVudC52MS5Sb29tU3RvcEdhbWVI",
            "AFIIc3RvcEdhbWUSRgoMZ2FtZV9yZXF1ZXN0GAggASgLMiEuY2hhdC5jbGll",
            "bnQudjEuQ2xpZW50R2FtZVJlcXVlc3RIAFILZ2FtZVJlcXVlc3RCBgoEZGF0",
            "YUKFAQoSY29tLmNoYXQuY2xpZW50LnYxQgxSZXF1ZXN0UHJvdG9QAVoHLi9w",
            "cm90b6ICA0NDWKoCDkNoYXQuQ2xpZW50LlYxygIOQ2hhdFxDbGllbnRcVjHi",
            "AhpDaGF0XENsaWVudFxWMVxHUEJNZXRhZGF0YeoCEENoYXQ6OkNsaWVudDo6",
            "VjFiCGVkaXRpb25zcOgH"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Chat.Client.V1.GameReflection.Descriptor, global::Chat.Client.V1.RoomReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Client.V1.ClientRequest), global::Chat.Client.V1.ClientRequest.Parser, new[]{ "Version", "CreateRoom", "GetRooms", "JoinRoom", "LeaveRoom", "StartGame", "StopGame", "GameRequest" }, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientRequest : pb::IMessage<ClientRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Client.V1.RequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest(ClientRequest other) : this() {
      version_ = other.version_;
      switch (other.DataCase) {
        case DataOneofCase.CreateRoom:
          CreateRoom = other.CreateRoom.Clone();
          break;
        case DataOneofCase.GetRooms:
          GetRooms = other.GetRooms.Clone();
          break;
        case DataOneofCase.JoinRoom:
          JoinRoom = other.JoinRoom.Clone();
          break;
        case DataOneofCase.LeaveRoom:
          LeaveRoom = other.LeaveRoom.Clone();
          break;
        case DataOneofCase.StartGame:
          StartGame = other.StartGame.Clone();
          break;
        case DataOneofCase.StopGame:
          StopGame = other.StopGame.Clone();
          break;
        case DataOneofCase.GameRequest:
          GameRequest = other.GameRequest.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest Clone() {
      return new ClientRequest(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private readonly static string VersionDefaultValue = "";

    private string version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_ ?? VersionDefaultValue; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "version" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVersion {
      get { return version_ != null; }
    }
    /// <summary>Clears the value of the "version" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVersion() {
      version_ = null;
    }

    /// <summary>Field number for the "create_room" field.</summary>
    public const int CreateRoomFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.CreateRoom CreateRoom {
      get { return dataCase_ == DataOneofCase.CreateRoom ? (global::Chat.Client.V1.CreateRoom) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.CreateRoom;
      }
    }

    /// <summary>Field number for the "get_rooms" field.</summary>
    public const int GetRoomsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.GetRooms GetRooms {
      get { return dataCase_ == DataOneofCase.GetRooms ? (global::Chat.Client.V1.GetRooms) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.GetRooms;
      }
    }

    /// <summary>Field number for the "join_room" field.</summary>
    public const int JoinRoomFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.JoinRoom JoinRoom {
      get { return dataCase_ == DataOneofCase.JoinRoom ? (global::Chat.Client.V1.JoinRoom) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.JoinRoom;
      }
    }

    /// <summary>Field number for the "leave_room" field.</summary>
    public const int LeaveRoomFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.LeaveRoom LeaveRoom {
      get { return dataCase_ == DataOneofCase.LeaveRoom ? (global::Chat.Client.V1.LeaveRoom) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LeaveRoom;
      }
    }

    /// <summary>Field number for the "start_game" field.</summary>
    public const int StartGameFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.RoomStartGame StartGame {
      get { return dataCase_ == DataOneofCase.StartGame ? (global::Chat.Client.V1.RoomStartGame) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.StartGame;
      }
    }

    /// <summary>Field number for the "stop_game" field.</summary>
    public const int StopGameFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.RoomStopGame StopGame {
      get { return dataCase_ == DataOneofCase.StopGame ? (global::Chat.Client.V1.RoomStopGame) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.StopGame;
      }
    }

    /// <summary>Field number for the "game_request" field.</summary>
    public const int GameRequestFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Client.V1.ClientGameRequest GameRequest {
      get { return dataCase_ == DataOneofCase.GameRequest ? (global::Chat.Client.V1.ClientGameRequest) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.GameRequest;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      CreateRoom = 2,
      GetRooms = 3,
      JoinRoom = 4,
      LeaveRoom = 5,
      StartGame = 6,
      StopGame = 7,
      GameRequest = 8,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (!object.Equals(CreateRoom, other.CreateRoom)) return false;
      if (!object.Equals(GetRooms, other.GetRooms)) return false;
      if (!object.Equals(JoinRoom, other.JoinRoom)) return false;
      if (!object.Equals(LeaveRoom, other.LeaveRoom)) return false;
      if (!object.Equals(StartGame, other.StartGame)) return false;
      if (!object.Equals(StopGame, other.StopGame)) return false;
      if (!object.Equals(GameRequest, other.GameRequest)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasVersion) hash ^= Version.GetHashCode();
      if (dataCase_ == DataOneofCase.CreateRoom) hash ^= CreateRoom.GetHashCode();
      if (dataCase_ == DataOneofCase.GetRooms) hash ^= GetRooms.GetHashCode();
      if (dataCase_ == DataOneofCase.JoinRoom) hash ^= JoinRoom.GetHashCode();
      if (dataCase_ == DataOneofCase.LeaveRoom) hash ^= LeaveRoom.GetHashCode();
      if (dataCase_ == DataOneofCase.StartGame) hash ^= StartGame.GetHashCode();
      if (dataCase_ == DataOneofCase.StopGame) hash ^= StopGame.GetHashCode();
      if (dataCase_ == DataOneofCase.GameRequest) hash ^= GameRequest.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasVersion) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      if (dataCase_ == DataOneofCase.CreateRoom) {
        output.WriteRawTag(18);
        output.WriteMessage(CreateRoom);
      }
      if (dataCase_ == DataOneofCase.GetRooms) {
        output.WriteRawTag(26);
        output.WriteMessage(GetRooms);
      }
      if (dataCase_ == DataOneofCase.JoinRoom) {
        output.WriteRawTag(34);
        output.WriteMessage(JoinRoom);
      }
      if (dataCase_ == DataOneofCase.LeaveRoom) {
        output.WriteRawTag(42);
        output.WriteMessage(LeaveRoom);
      }
      if (dataCase_ == DataOneofCase.StartGame) {
        output.WriteRawTag(50);
        output.WriteMessage(StartGame);
      }
      if (dataCase_ == DataOneofCase.StopGame) {
        output.WriteRawTag(58);
        output.WriteMessage(StopGame);
      }
      if (dataCase_ == DataOneofCase.GameRequest) {
        output.WriteRawTag(66);
        output.WriteMessage(GameRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasVersion) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      if (dataCase_ == DataOneofCase.CreateRoom) {
        output.WriteRawTag(18);
        output.WriteMessage(CreateRoom);
      }
      if (dataCase_ == DataOneofCase.GetRooms) {
        output.WriteRawTag(26);
        output.WriteMessage(GetRooms);
      }
      if (dataCase_ == DataOneofCase.JoinRoom) {
        output.WriteRawTag(34);
        output.WriteMessage(JoinRoom);
      }
      if (dataCase_ == DataOneofCase.LeaveRoom) {
        output.WriteRawTag(42);
        output.WriteMessage(LeaveRoom);
      }
      if (dataCase_ == DataOneofCase.StartGame) {
        output.WriteRawTag(50);
        output.WriteMessage(StartGame);
      }
      if (dataCase_ == DataOneofCase.StopGame) {
        output.WriteRawTag(58);
        output.WriteMessage(StopGame);
      }
      if (dataCase_ == DataOneofCase.GameRequest) {
        output.WriteRawTag(66);
        output.WriteMessage(GameRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasVersion) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (dataCase_ == DataOneofCase.CreateRoom) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateRoom);
      }
      if (dataCase_ == DataOneofCase.GetRooms) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRooms);
      }
      if (dataCase_ == DataOneofCase.JoinRoom) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JoinRoom);
      }
      if (dataCase_ == DataOneofCase.LeaveRoom) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaveRoom);
      }
      if (dataCase_ == DataOneofCase.StartGame) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartGame);
      }
      if (dataCase_ == DataOneofCase.StopGame) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StopGame);
      }
      if (dataCase_ == DataOneofCase.GameRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasVersion) {
        Version = other.Version;
      }
      switch (other.DataCase) {
        case DataOneofCase.CreateRoom:
          if (CreateRoom == null) {
            CreateRoom = new global::Chat.Client.V1.CreateRoom();
          }
          CreateRoom.MergeFrom(other.CreateRoom);
          break;
        case DataOneofCase.GetRooms:
          if (GetRooms == null) {
            GetRooms = new global::Chat.Client.V1.GetRooms();
          }
          GetRooms.MergeFrom(other.GetRooms);
          break;
        case DataOneofCase.JoinRoom:
          if (JoinRoom == null) {
            JoinRoom = new global::Chat.Client.V1.JoinRoom();
          }
          JoinRoom.MergeFrom(other.JoinRoom);
          break;
        case DataOneofCase.LeaveRoom:
          if (LeaveRoom == null) {
            LeaveRoom = new global::Chat.Client.V1.LeaveRoom();
          }
          LeaveRoom.MergeFrom(other.LeaveRoom);
          break;
        case DataOneofCase.StartGame:
          if (StartGame == null) {
            StartGame = new global::Chat.Client.V1.RoomStartGame();
          }
          StartGame.MergeFrom(other.StartGame);
          break;
        case DataOneofCase.StopGame:
          if (StopGame == null) {
            StopGame = new global::Chat.Client.V1.RoomStopGame();
          }
          StopGame.MergeFrom(other.StopGame);
          break;
        case DataOneofCase.GameRequest:
          if (GameRequest == null) {
            GameRequest = new global::Chat.Client.V1.ClientGameRequest();
          }
          GameRequest.MergeFrom(other.GameRequest);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            global::Chat.Client.V1.CreateRoom subBuilder = new global::Chat.Client.V1.CreateRoom();
            if (dataCase_ == DataOneofCase.CreateRoom) {
              subBuilder.MergeFrom(CreateRoom);
            }
            input.ReadMessage(subBuilder);
            CreateRoom = subBuilder;
            break;
          }
          case 26: {
            global::Chat.Client.V1.GetRooms subBuilder = new global::Chat.Client.V1.GetRooms();
            if (dataCase_ == DataOneofCase.GetRooms) {
              subBuilder.MergeFrom(GetRooms);
            }
            input.ReadMessage(subBuilder);
            GetRooms = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Client.V1.JoinRoom subBuilder = new global::Chat.Client.V1.JoinRoom();
            if (dataCase_ == DataOneofCase.JoinRoom) {
              subBuilder.MergeFrom(JoinRoom);
            }
            input.ReadMessage(subBuilder);
            JoinRoom = subBuilder;
            break;
          }
          case 42: {
            global::Chat.Client.V1.LeaveRoom subBuilder = new global::Chat.Client.V1.LeaveRoom();
            if (dataCase_ == DataOneofCase.LeaveRoom) {
              subBuilder.MergeFrom(LeaveRoom);
            }
            input.ReadMessage(subBuilder);
            LeaveRoom = subBuilder;
            break;
          }
          case 50: {
            global::Chat.Client.V1.RoomStartGame subBuilder = new global::Chat.Client.V1.RoomStartGame();
            if (dataCase_ == DataOneofCase.StartGame) {
              subBuilder.MergeFrom(StartGame);
            }
            input.ReadMessage(subBuilder);
            StartGame = subBuilder;
            break;
          }
          case 58: {
            global::Chat.Client.V1.RoomStopGame subBuilder = new global::Chat.Client.V1.RoomStopGame();
            if (dataCase_ == DataOneofCase.StopGame) {
              subBuilder.MergeFrom(StopGame);
            }
            input.ReadMessage(subBuilder);
            StopGame = subBuilder;
            break;
          }
          case 66: {
            global::Chat.Client.V1.ClientGameRequest subBuilder = new global::Chat.Client.V1.ClientGameRequest();
            if (dataCase_ == DataOneofCase.GameRequest) {
              subBuilder.MergeFrom(GameRequest);
            }
            input.ReadMessage(subBuilder);
            GameRequest = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            global::Chat.Client.V1.CreateRoom subBuilder = new global::Chat.Client.V1.CreateRoom();
            if (dataCase_ == DataOneofCase.CreateRoom) {
              subBuilder.MergeFrom(CreateRoom);
            }
            input.ReadMessage(subBuilder);
            CreateRoom = subBuilder;
            break;
          }
          case 26: {
            global::Chat.Client.V1.GetRooms subBuilder = new global::Chat.Client.V1.GetRooms();
            if (dataCase_ == DataOneofCase.GetRooms) {
              subBuilder.MergeFrom(GetRooms);
            }
            input.ReadMessage(subBuilder);
            GetRooms = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Client.V1.JoinRoom subBuilder = new global::Chat.Client.V1.JoinRoom();
            if (dataCase_ == DataOneofCase.JoinRoom) {
              subBuilder.MergeFrom(JoinRoom);
            }
            input.ReadMessage(subBuilder);
            JoinRoom = subBuilder;
            break;
          }
          case 42: {
            global::Chat.Client.V1.LeaveRoom subBuilder = new global::Chat.Client.V1.LeaveRoom();
            if (dataCase_ == DataOneofCase.LeaveRoom) {
              subBuilder.MergeFrom(LeaveRoom);
            }
            input.ReadMessage(subBuilder);
            LeaveRoom = subBuilder;
            break;
          }
          case 50: {
            global::Chat.Client.V1.RoomStartGame subBuilder = new global::Chat.Client.V1.RoomStartGame();
            if (dataCase_ == DataOneofCase.StartGame) {
              subBuilder.MergeFrom(StartGame);
            }
            input.ReadMessage(subBuilder);
            StartGame = subBuilder;
            break;
          }
          case 58: {
            global::Chat.Client.V1.RoomStopGame subBuilder = new global::Chat.Client.V1.RoomStopGame();
            if (dataCase_ == DataOneofCase.StopGame) {
              subBuilder.MergeFrom(StopGame);
            }
            input.ReadMessage(subBuilder);
            StopGame = subBuilder;
            break;
          }
          case 66: {
            global::Chat.Client.V1.ClientGameRequest subBuilder = new global::Chat.Client.V1.ClientGameRequest();
            if (dataCase_ == DataOneofCase.GameRequest) {
              subBuilder.MergeFrom(GameRequest);
            }
            input.ReadMessage(subBuilder);
            GameRequest = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
